"""Compress the four UI pages into flash-resident gzip blobs.

The pages are authored as readable HTML in lib/WebServer/src/*UI.h, each split
into spans that this script joins with the shared dialog from UIDialog.h.
Stored verbatim the four pages cost about 198 KB of a 1.5 MB app partition;
gzipped they cost about 47 KB, and every browser inflates them for free.
Sharing the dialog spans between pages stopped paying once each page became a
single deflate stream, so the joining moved out of UIPages.hpp and to here.

Runs as a PlatformIO pre-script and standalone for the ad-hoc g++ tests:

    python3 scripts/build_ui_gz.py
"""
import gzip
import io
import re
from pathlib import Path

UI_SOURCE = Path('lib') / 'WebServer' / 'src'
GENERATED = 'UIPagesGz.h'

# Each page is HEAD, the shared dialog CSS, BODY, the shared dialog script,
# then the page script. Keep in step with the <style>/<script> seams the
# page sources leave open at the end of each span.
PAGES = (
    ('WEB_UI', 'WebUI.h'),
    ('MANUAL_UI', 'ManualUI.h'),
    ('SETTINGS_UI', 'SettingsUI.h'),
    ('FILE_UI', 'FileUI.h'),
)
LITERAL = re.compile(r'const char (\w+)\[\] PROGMEM = R"(\w+)\(', re.MULTILINE)


def literals(path):
    """Every raw string literal in one page source, by name."""
    text = path.read_text()
    found = {}
    for match in LITERAL.finditer(text):
        name, tag = match.group(1), match.group(2)
        start = match.end()
        end = text.find(')' + tag + '"', start)
        if end < 0:
            raise RuntimeError(f'Unterminated literal {name} in {path.name}')
        found[name] = text[start:end]
    if not found:
        raise RuntimeError(f'No PROGMEM literals in {path.name}')
    return found


def compress(data):
    """gzip with no timestamp, so an unchanged page regenerates byte-for-byte."""
    buffer = io.BytesIO()
    with gzip.GzipFile(fileobj=buffer, mode='wb', compresslevel=9, mtime=0) as out:
        out.write(data.encode())
    return buffer.getvalue()


def render(source):
    dialog = literals(source / 'UIDialog.h')
    lines = [
        '#pragma once',
        '// Generated by scripts/build_ui_gz.py -- do not edit.',
        '// Sources: UIDialog.h and the four *UI.h pages. See UIPages.hpp.',
        '',
        '#include <cstddef>',
        '#include <cstdint>',
        '',
    ]
    for prefix, filename in PAGES:
        page = literals(source / filename)
        joined = (page[prefix + '_HEAD'] + dialog['UI_DIALOG_CSS'] +
                  page[prefix + '_BODY'] + dialog['UI_DIALOG_JS'] +
                  page[prefix + '_SCRIPT'])
        blob = compress(joined)
        body = ','.join(f'0x{byte:02x}' for byte in blob)
        wrapped = re.sub(r'((?:0x[0-9a-f]{2},){15}0x[0-9a-f]{2},?)', r'\1\n    ', body)
        lines += [
            f'// {len(joined)} bytes of HTML in {len(blob)} bytes of gzip.',
            f'const uint8_t {prefix}_GZ[] PROGMEM = {{',
            '    ' + wrapped.rstrip(),
            '};',
            '',
        ]
    return '\n'.join(lines)


def build(root):
    source = Path(root) / UI_SOURCE
    header = source / GENERATED
    generated = render(source)
    # Rewriting an identical header would relink every dependent object.
    if not header.exists() or header.read_text() != generated:
        header.write_text(generated)


if __name__ == '__main__':
    build(Path(__file__).resolve().parent.parent)
elif 'Import' in globals():
    # PlatformIO execs this without __file__; it knows the project root.
    Import('env')  # noqa: F821 - PlatformIO/SCons
    build(env.subst('$PROJECT_DIR'))  # noqa: F821 - PlatformIO/SCons
